# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '商品评论详情',
                'verbose_name_plural': '商品评论详情',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='商品标题')),
                ('content', models.TextField(verbose_name='商品详情')),
                ('original_price', models.FloatField(verbose_name='原价')),
                ('current_price', models.FloatField(verbose_name='现价')),
                ('created_time', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='good.Category')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=254, null=True, unique=True, verbose_name='图片存储路径')),
                ('is_main_pic', models.SmallIntegerField(choices=[(0, '非主图'), (1, '主图')], default=0, verbose_name='是否是主图')),
                ('good', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='good.Good', verbose_name='对应商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='GoodStatusAndSellMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_number', models.CharField(max_length=50, unique=True)),
                ('status_content', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '商品及交易方式',
                'verbose_name_plural': '商品及交易方式',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='good_status',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_status', to='good.GoodStatusAndSellMethod', verbose_name='商品状态'),
        ),
    ]
