# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_time', models.DateField(auto_now_add=True, null=True)),
                ('create_user', models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '商品评论详情',
                'verbose_name_plural': '商品评论详情',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='商品标题')),
                ('content', models.TextField(verbose_name='商品详情')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='原价')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='现价')),
                ('sell_method', models.PositiveIntegerField(choices=[(0, '同城当面交易'), (1, '快递'), (2, '不限交易方式')], default=2, verbose_name='交易方式')),
                ('category', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='good.Category')),
                ('owner_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_owner_user', to=settings.AUTH_USER_MODEL, verbose_name='商品发布者')),
                ('star_users', models.ManyToManyField(db_constraint=False, related_name='good_star_users', to=settings.AUTH_USER_MODEL, verbose_name='关注用户')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('is_main_pic', models.BooleanField(default=0, verbose_name='是否是主图')),
                ('good', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='good.Good', verbose_name='对应商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='good',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='good.Good', verbose_name='评论商品'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='good.Comment', verbose_name='父评价'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
    ]
