# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('good', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='owner_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_owner_user', to=settings.AUTH_USER_MODEL, verbose_name='商品发布者'),
        ),
        migrations.AddField(
            model_name='good',
            name='sell_method',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_sell_method', to='good.GoodStatusAndSellMethod', verbose_name='交易方式'),
        ),
        migrations.AddField(
            model_name='good',
            name='star_users',
            field=models.ManyToManyField(db_constraint=False, related_name='good_star_users', to=settings.AUTH_USER_MODEL, verbose_name='关注用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='good',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='good.Good', verbose_name='评论商品'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='good.Comment', verbose_name='父评价'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
    ]
