# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20190418_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
