# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20190408_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='good_statuc',
            field=models.SmallIntegerField(choices=[(0, '在售'), (1, '已售出')], default=0, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sell_method',
            field=models.SmallIntegerField(choices=[(0, '同城当面交易'), (1, '快递'), (2, '不限交易方式')], default=2, verbose_name='交易方式'),
        ),
    ]
