# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_category_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_status',
            field=models.ForeignKey(db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_status', to='good.GoodStatusAndSellMethod', verbose_name='商品状态'),
        ),
    ]
