# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0004_auto_20190408_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
