# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0007_good_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodpictures',
            name='image',
        ),
        migrations.AddField(
            model_name='goodpictures',
            name='image_path',
            field=models.CharField(max_length=254, null=True, unique=True, verbose_name='图片存储路径'),
        ),
        migrations.AlterField(
            model_name='goodpictures',
            name='is_main_pic',
            field=models.SmallIntegerField(choices=[(0, '非主图'), (1, '主图')], default=0, verbose_name='是否是主图'),
        ),
    ]
