# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0008_auto_20190411_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodStatusAndSellMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_number', models.CharField(max_length=50)),
                ('status_content', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '商品及交易方式',
                'verbose_name_plural': '商品及交易方式',
            },
        ),
        migrations.AlterUniqueTogether(
            name='goodstatusandsellmethod',
            unique_together=set([('status_number', 'status_content')]),
        ),
    ]
