# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0009_auto_20190412_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstatusandsellmethod',
            name='status_content',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='goodstatusandsellmethod',
            name='status_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='goodstatusandsellmethod',
            unique_together=set([]),
        ),
    ]
