# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0010_auto_20190412_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_status',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_statusr', to='good.GoodStatusAndSellMethod', verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sell_method',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_sell_method', to='good.GoodStatusAndSellMethod', verbose_name='交易方式'),
        ),
    ]
