# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0012_auto_20190415_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='current_price',
            field=models.FloatField(verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='good',
            name='original_price',
            field=models.FloatField(verbose_name='原价'),
        ),
    ]
