# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 14:44
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.BigIntegerField(verbose_name='手机号')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='用户注册日期')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='余额')),
                ('user_type', models.IntegerField(choices=[(0, '普通用户'), (1, '超级用户'), (2, '冻结用户')], default=2, verbose_name='用户类型')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='交易金额')),
                ('created_time', models.DateField(auto_now_add=True, null=True, verbose_name='交易创建时间')),
                ('bill_status', models.IntegerField(choices=[(0, '买家已付款'), (1, '卖家已收款'), (3, '买家已申请退款'), (4, '卖家已退款')], default=0, verbose_name='钱款状态')),
                ('buyer', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_buyer', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('seller', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_seller', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '钱款详情',
                'verbose_name_plural': '钱款详情',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='聊天时间')),
                ('content', models.TextField(verbose_name='聊天内容')),
            ],
            options={
                'verbose_name': '聊天记录',
                'verbose_name_plural': '聊天记录',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '商品评论详情',
                'verbose_name_plural': '商品评论详情',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='商品标题')),
                ('content', models.TextField(verbose_name='商品详情')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='原价')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='现价')),
                ('sell_method', models.PositiveIntegerField(choices=[(0, '同城当面交易'), (1, '快递'), (2, '不限交易方式')], default=2, verbose_name='交易方式')),
                ('owner_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_owner_user', to=settings.AUTH_USER_MODEL, verbose_name='商品发布者')),
                ('star_users', models.ManyToManyField(db_constraint=False, related_name='good_star_users', to=settings.AUTH_USER_MODEL, verbose_name='关注用户')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('is_main_pic', models.BooleanField(default=0, verbose_name='是否是主图')),
                ('good', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Good', verbose_name='对应商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_number', models.BigIntegerField(verbose_name='身份证号')),
                ('id_card_pic', models.ImageField(upload_to='', verbose_name='身份证图片')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户身份证验证',
                'verbose_name_plural': '用户身份证验证',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.PositiveIntegerField(choices=[(0, '卖家未发货'), (1, '卖家已发货'), (2, '买家已收货'), (3, '买家已退货'), (4, '卖家已收货')], default=0, verbose_name='订单状态')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='订单生成时间')),
                ('buyer', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_buyer', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('cash_flow_history', models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.CashFlow', verbose_name='钱款')),
                ('seller', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_seller', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=64, verbose_name='收件人姓名')),
                ('receiver_telephone', models.BigIntegerField(verbose_name='收件人手机')),
                ('receiver_address', models.TextField(verbose_name='收件人地址')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收件地址',
                'verbose_name_plural': '用户收件地址',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='good',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Good', verbose_name='评论商品'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Comment', verbose_name='父评价'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='good',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Good', verbose_name='聊天相关商品'),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='receiver',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_receiver', to=settings.AUTH_USER_MODEL, verbose_name='接收方'),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='sender',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sender', to=settings.AUTH_USER_MODEL, verbose_name='发送方'),
        ),
        migrations.AddField(
            model_name='category',
            name='good',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Good'),
        ),
    ]
