# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='余额'),
        ),
    ]
