# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190425_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='receiver',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_receiver', to=settings.AUTH_USER_MODEL, verbose_name='接收方'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='sender',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sender', to=settings.AUTH_USER_MODEL, verbose_name='发送方'),
        ),
    ]
