# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190402_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cash_flow_history',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(null=True, verbose_name='交易金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_status',
            field=models.IntegerField(choices=[(0, '买家已付款'), (1, '卖家已收款'), (3, '买家已申请退款'), (4, '卖家已退款')], default=0, verbose_name='钱款状态'),
        ),
        migrations.DeleteModel(
            name='CashFlow',
        ),
    ]
