# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190402_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.BigIntegerField()),
                ('delivery_company', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '运单',
                'verbose_name_plural': '运单',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Delivery'),
        ),
    ]
