# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190402_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delicery_account',
            field=models.PositiveIntegerField(null=True, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.BigIntegerField(unique=True, verbose_name='手机号'),
        ),
    ]
