# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190407_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.BigIntegerField(unique=True, verbose_name='手机号'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([]),
        ),
    ]
