# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190407_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone_status',
            field=models.PositiveIntegerField(choices=[(0, '未验证'), (1, '已验证')], default=0),
        ),
    ]
