# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good', '0002_auto_20190417_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.BigIntegerField(verbose_name='订单号')),
                ('delivery_company', models.CharField(max_length=64, verbose_name='快递公司')),
                ('receive_address', models.TextField(verbose_name='收货地址')),
                ('send_address', models.TextField(verbose_name='发货地址')),
            ],
            options={
                'verbose_name': '运单',
                'verbose_name_plural': '运单',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, unique=True, verbose_name='订单号')),
                ('order_title', models.TextField(verbose_name='商品标题')),
                ('delivery_price', models.FloatField(verbose_name='运费')),
                ('order_price', models.FloatField(verbose_name='订单金额')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='订单生成时间')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusAndBillStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_number', models.SmallIntegerField(unique=True, verbose_name='状态编号')),
                ('status_content', models.CharField(max_length=128, unique=True, verbose_name='状态内容')),
            ],
            options={
                'verbose_name': '订单状态和钱款状态',
                'verbose_name_plural': '订单状态和钱款状态',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='bill_status',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_status', to='order.OrderStatusAndBillStatus', verbose_name='钱款状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='买家'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Delivery', verbose_name='快递'),
        ),
        migrations.AddField(
            model_name='order',
            name='good',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='good.Good', verbose_name='订单对应商品'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status', to='order.OrderStatusAndBillStatus', verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
        ),
    ]
