# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.BigIntegerField(verbose_name='订单号')),
                ('delivery_company', models.CharField(max_length=64, verbose_name='快递公司')),
                ('receive_address', models.TextField(verbose_name='收货地址')),
                ('send_address', models.TextField(verbose_name='发货地址')),
            ],
            options={
                'verbose_name': '运单',
                'verbose_name_plural': '运单',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, unique=True, verbose_name='订单号')),
                ('order_title', models.TextField(verbose_name='商品标题')),
                ('delivery_price', models.FloatField(verbose_name='运费')),
                ('order_price', models.FloatField(verbose_name='订单金额')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='订单生成时间')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusAndBillStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_number', models.SmallIntegerField(unique=True, verbose_name='状态编号')),
                ('status_content', models.CharField(max_length=128, unique=True, verbose_name='状态内容')),
            ],
            options={
                'verbose_name': '订单状态和钱款状态',
                'verbose_name_plural': '订单状态和钱款状态',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='bill_status',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_status', to='order.OrderStatusAndBillStatus', verbose_name='钱款状态'),
        ),
    ]
