# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190418_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_show',
            field=models.IntegerField(default=1, verbose_name='订单是否显示'),
        ),
    ]
