# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_order_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_owner',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_owner', to=settings.AUTH_USER_MODEL, verbose_name='订单主人'),
        ),
    ]
