# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_show',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_is_show',
            field=models.IntegerField(default=1, verbose_name='买家是否显示订单'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_is_show',
            field=models.IntegerField(default=1, verbose_name='买家是否显示订单'),
        ),
    ]
