# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190425_1909'),
        ('order', '0006_auto_20190418_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='receive_address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='send_address',
        ),
        migrations.AddField(
            model_name='delivery',
            name='receiver_address',
            field=models.TextField(null=True, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='receiver_name',
            field=models.CharField(max_length=128, null=True, verbose_name='收货人姓名'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='receiver_telephone',
            field=models.CharField(max_length=128, null=True, verbose_name='收货人手机'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sender_address',
            field=models.TextField(null=True, verbose_name='发货人地址'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sender_name',
            field=models.TextField(null=True, verbose_name='发货人姓名'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sender_telephone',
            field=models.CharField(max_length=128, null=True, verbose_name='发货人手机'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_address',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_buyer_address', to='user.UserAddress', verbose_name='订单收货人信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='drawback_delivery',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawback_delivery', to='order.Delivery', verbose_name='退货快递'),
        ),
        migrations.AddField(
            model_name='order',
            name='drawback_delivery_price',
            field=models.FloatField(null=True, verbose_name='退货运费'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_address',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_seller_address', to='user.UserAddress', verbose_name='订单发货人信息'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_company',
            field=models.CharField(max_length=64, null=True, verbose_name='快递公司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_status', to='order.OrderStatusAndBillStatus', verbose_name='钱款状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='order.Delivery', verbose_name='快递'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.FloatField(default=0, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status', to='order.OrderStatusAndBillStatus', verbose_name='订单状态'),
        ),
    ]
